version: '3.8'

services:
  # Test PostgreSQL Database
  postgres-test:
    image: postgres:16-alpine
    container_name: discord-bot-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discord_bot_test
    ports:
      - "5433:5432"
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Test Redis Cache
  redis-test:
    image: redis:7-alpine
    container_name: discord-bot-redis-test
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6380:6379"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  test-network:
    driver: bridge