import { z } from 'zod';
declare const envSchema: z.ZodEffects<z.ZodObject<{
    DISCORD_TOKEN: z.ZodString;
    DISCORD_APPLICATION_ID: z.ZodString;
    DISCORD_GUILD_ID: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodEffects<z.ZodString, string, string>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    LAVALINK_HOST: z.ZodDefault<z.ZodString>;
    LAVALINK_PORT: z.ZodDefault<z.ZodNumber>;
    LAVALINK_PASSWORD: z.ZodString;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodOptional<z.ZodString>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    SENTRY_ENVIRONMENT: z.ZodDefault<z.ZodEnum<["development", "staging", "production", "test"]>>;
    SENTRY_TRACES_SAMPLE_RATE: z.ZodDefault<z.ZodNumber>;
    SENTRY_PROFILES_SAMPLE_RATE: z.ZodDefault<z.ZodNumber>;
    GATEWAY_HTTP_PORT: z.ZodDefault<z.ZodNumber>;
    AUDIO_HTTP_PORT: z.ZodDefault<z.ZodNumber>;
    WORKER_HTTP_PORT: z.ZodDefault<z.ZodNumber>;
    DJ_ROLE_NAME: z.ZodDefault<z.ZodString>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "staging", "production", "test"]>>;
    API_KEY: z.ZodOptional<z.ZodString>;
    NOWPLAYING_UPDATE_MS: z.ZodDefault<z.ZodNumber>;
    COMMANDS_CLEANUP_ON_START: z.ZodDefault<z.ZodBoolean>;
    COMMANDS_SCOPE: z.ZodDefault<z.ZodEnum<["global", "guild", "both"]>>;
    SPOTIFY_CLIENT_ID: z.ZodOptional<z.ZodString>;
    SPOTIFY_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    DEEZER_ARL: z.ZodOptional<z.ZodString>;
    APPLE_MUSIC_MEDIA_TOKEN: z.ZodOptional<z.ZodString>;
    PREMIUM_TEST_GUILD_IDS: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "test" | "development" | "staging" | "production";
    DISCORD_TOKEN: string;
    DISCORD_APPLICATION_ID: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    LAVALINK_HOST: string;
    LAVALINK_PORT: number;
    LAVALINK_PASSWORD: string;
    SENTRY_ENVIRONMENT: "test" | "development" | "staging" | "production";
    SENTRY_TRACES_SAMPLE_RATE: number;
    SENTRY_PROFILES_SAMPLE_RATE: number;
    GATEWAY_HTTP_PORT: number;
    AUDIO_HTTP_PORT: number;
    WORKER_HTTP_PORT: number;
    DJ_ROLE_NAME: string;
    NOWPLAYING_UPDATE_MS: number;
    COMMANDS_CLEANUP_ON_START: boolean;
    COMMANDS_SCOPE: "global" | "guild" | "both";
    DISCORD_GUILD_ID?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    SENTRY_DSN?: string | undefined;
    API_KEY?: string | undefined;
    SPOTIFY_CLIENT_ID?: string | undefined;
    SPOTIFY_CLIENT_SECRET?: string | undefined;
    DEEZER_ARL?: string | undefined;
    APPLE_MUSIC_MEDIA_TOKEN?: string | undefined;
    PREMIUM_TEST_GUILD_IDS?: string | undefined;
}, {
    DISCORD_TOKEN: string;
    DISCORD_APPLICATION_ID: string;
    DATABASE_URL: string;
    LAVALINK_PASSWORD: string;
    NODE_ENV?: "test" | "development" | "staging" | "production" | undefined;
    DISCORD_GUILD_ID?: string | undefined;
    REDIS_URL?: string | undefined;
    LAVALINK_HOST?: string | undefined;
    LAVALINK_PORT?: number | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ENVIRONMENT?: "test" | "development" | "staging" | "production" | undefined;
    SENTRY_TRACES_SAMPLE_RATE?: number | undefined;
    SENTRY_PROFILES_SAMPLE_RATE?: number | undefined;
    GATEWAY_HTTP_PORT?: number | undefined;
    AUDIO_HTTP_PORT?: number | undefined;
    WORKER_HTTP_PORT?: number | undefined;
    DJ_ROLE_NAME?: string | undefined;
    API_KEY?: string | undefined;
    NOWPLAYING_UPDATE_MS?: number | undefined;
    COMMANDS_CLEANUP_ON_START?: boolean | undefined;
    COMMANDS_SCOPE?: "global" | "guild" | "both" | undefined;
    SPOTIFY_CLIENT_ID?: string | undefined;
    SPOTIFY_CLIENT_SECRET?: string | undefined;
    DEEZER_ARL?: string | undefined;
    APPLE_MUSIC_MEDIA_TOKEN?: string | undefined;
    PREMIUM_TEST_GUILD_IDS?: string | undefined;
}>, {
    NODE_ENV: "test" | "development" | "staging" | "production";
    DISCORD_TOKEN: string;
    DISCORD_APPLICATION_ID: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    LAVALINK_HOST: string;
    LAVALINK_PORT: number;
    LAVALINK_PASSWORD: string;
    SENTRY_ENVIRONMENT: "test" | "development" | "staging" | "production";
    SENTRY_TRACES_SAMPLE_RATE: number;
    SENTRY_PROFILES_SAMPLE_RATE: number;
    GATEWAY_HTTP_PORT: number;
    AUDIO_HTTP_PORT: number;
    WORKER_HTTP_PORT: number;
    DJ_ROLE_NAME: string;
    NOWPLAYING_UPDATE_MS: number;
    COMMANDS_CLEANUP_ON_START: boolean;
    COMMANDS_SCOPE: "global" | "guild" | "both";
    DISCORD_GUILD_ID?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    SENTRY_DSN?: string | undefined;
    API_KEY?: string | undefined;
    SPOTIFY_CLIENT_ID?: string | undefined;
    SPOTIFY_CLIENT_SECRET?: string | undefined;
    DEEZER_ARL?: string | undefined;
    APPLE_MUSIC_MEDIA_TOKEN?: string | undefined;
    PREMIUM_TEST_GUILD_IDS?: string | undefined;
}, {
    DISCORD_TOKEN: string;
    DISCORD_APPLICATION_ID: string;
    DATABASE_URL: string;
    LAVALINK_PASSWORD: string;
    NODE_ENV?: "test" | "development" | "staging" | "production" | undefined;
    DISCORD_GUILD_ID?: string | undefined;
    REDIS_URL?: string | undefined;
    LAVALINK_HOST?: string | undefined;
    LAVALINK_PORT?: number | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ENVIRONMENT?: "test" | "development" | "staging" | "production" | undefined;
    SENTRY_TRACES_SAMPLE_RATE?: number | undefined;
    SENTRY_PROFILES_SAMPLE_RATE?: number | undefined;
    GATEWAY_HTTP_PORT?: number | undefined;
    AUDIO_HTTP_PORT?: number | undefined;
    WORKER_HTTP_PORT?: number | undefined;
    DJ_ROLE_NAME?: string | undefined;
    API_KEY?: string | undefined;
    NOWPLAYING_UPDATE_MS?: number | undefined;
    COMMANDS_CLEANUP_ON_START?: boolean | undefined;
    COMMANDS_SCOPE?: "global" | "guild" | "both" | undefined;
    SPOTIFY_CLIENT_ID?: string | undefined;
    SPOTIFY_CLIENT_SECRET?: string | undefined;
    DEEZER_ARL?: string | undefined;
    APPLE_MUSIC_MEDIA_TOKEN?: string | undefined;
    PREMIUM_TEST_GUILD_IDS?: string | undefined;
}>;
export type Environment = 'development' | 'staging' | 'production' | 'test';
export type Env = z.infer<typeof envSchema> & {
    SPOTIFY_ENABLED: boolean;
    DEEZER_ENABLED: boolean;
    APPLE_ENABLED: boolean;
    PREMIUM_TEST_GUILD_IDS_LIST: string[];
};
declare let env: Env;
export { env };
export * from './premium-features.js';
export * from './enhanced-premium-config.js';
export type { FeatureName, PeriodType, FeatureCategory, AudioQualityLevel, Tier, Quality } from './enhanced-premium-config.js';
export { hasFeatureAccess, getAvailableFeatures, getQuotaForTier, getRestrictionForTier, calculatePriceWithPeriod, getFeaturesByCategory, validateUsageQuota } from './enhanced-premium-config.js';
export { ENHANCED_PREMIUM_FEATURES, FEATURE_CATEGORIES, FEATURE_TIER_REQUIREMENTS, BILLING_PERIODS, ENHANCED_PRICING, FEATURE_ROLLOUT } from './enhanced-premium-config.js';
//# sourceMappingURL=index.d.ts.map